from django.urls import path

from .views import (
    DashboardView,
    DailyActivityStatsView,
    DepartmentStatsView,
    DepartmentTreeView,
    DepartmentInactiveListView,
    DepartmentCreateView,
    DepartmentUpdateView,
    DepartmentDeactivateView,
    DepartmentActivateView,
    HealthView,
    LoginView,
    MeView,
    MetaView,
    PeopleStatsView,
    RegisterView,
    StatusStatsView,
    TaskActionView,
    TaskCommentsView,
    TaskDetailUpdateView,
    TaskListCreateView,
    TaskNotificationListView,
    TaskNotificationReadView,
    TaskReminderView,
    UserListView,
    UserUpdateView,
    UserDeactivateView,
    UserActivateView,
    UserResetPasswordView,
    UserDeleteView,
    UserTransferTasksView,
)

urlpatterns = [
    path("health/", HealthView.as_view()),
    path("auth/register/", RegisterView.as_view()),
    path("auth/login/", LoginView.as_view()),
    path("auth/me/", MeView.as_view()),
    path("tasks/", TaskListCreateView.as_view()),
    path("tasks/<int:pk>/", TaskDetailUpdateView.as_view()),
    path("tasks/<int:pk>/actions/", TaskActionView.as_view()),
    path("tasks/<int:pk>/comments/", TaskCommentsView.as_view()),
    path("tasks/<int:pk>/reminders/", TaskReminderView.as_view()),
    path("notifications/", TaskNotificationListView.as_view()),
    path("notifications/<int:pk>/read/", TaskNotificationReadView.as_view()),
    path("dashboard/", DashboardView.as_view()),
    path("stats/people/", PeopleStatsView.as_view()),
    path("stats/departments/", DepartmentStatsView.as_view()),
    path("stats/statuses/", StatusStatsView.as_view()),
    path("stats/daily-activity/", DailyActivityStatsView.as_view()),
    path("meta/", MetaView.as_view()),
    # 组织管理 API
    path("org/departments/tree/", DepartmentTreeView.as_view()),
    path("org/departments/inactive/", DepartmentInactiveListView.as_view()),
    path("org/departments/", DepartmentCreateView.as_view()),
    path("org/departments/<int:pk>/", DepartmentUpdateView.as_view()),
    path("org/departments/<int:pk>/deactivate/", DepartmentDeactivateView.as_view()),
    path("org/departments/<int:pk>/activate/", DepartmentActivateView.as_view()),
    path("org/users/", UserListView.as_view()),
    path("org/users/<int:pk>/", UserUpdateView.as_view()),
    path("org/users/<int:pk>/deactivate/", UserDeactivateView.as_view()),
    path("org/users/<int:pk>/activate/", UserActivateView.as_view()),
    path("org/users/<int:pk>/reset-password/", UserResetPasswordView.as_view()),
    path("org/users/<int:pk>/delete/", UserDeleteView.as_view()),
    path("org/users/<int:pk>/transfer-tasks/", UserTransferTasksView.as_view()),
]
