# Generated by Django 4.2.20 on 2026-04-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="cancel_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flowevent",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("todo", "待处理"),
                    ("in_progress", "处理中"),
                    ("confirming", "待确认"),
                    ("acceptance", "验收中"),
                    ("overdue", "已超时"),
                    ("done", "已完成"),
                    ("cancel_pending", "待取消确认"),
                    ("cancelled", "已取消"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="flowevent",
            name="to_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("todo", "待处理"),
                    ("in_progress", "处理中"),
                    ("confirming", "待确认"),
                    ("acceptance", "验收中"),
                    ("overdue", "已超时"),
                    ("done", "已完成"),
                    ("cancel_pending", "待取消确认"),
                    ("cancelled", "已取消"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "待处理"),
                    ("in_progress", "处理中"),
                    ("confirming", "待确认"),
                    ("acceptance", "验收中"),
                    ("overdue", "已超时"),
                    ("done", "已完成"),
                    ("cancel_pending", "待取消确认"),
                    ("cancelled", "已取消"),
                ],
                default="todo",
                max_length=24,
            ),
        ),
    ]
