# Generated by Django 4.2.20 on 2026-04-24 17:36

from django.db import migrations, models


def migrate_acceptance_tasks(apps, schema_editor):
    """将验收中状态的任务改为待确认状态"""
    Task = apps.get_model("tasks", "Task")
    FlowEvent = apps.get_model("tasks", "FlowEvent")
    # 将验收中任务改为待确认
    Task.objects.filter(status="acceptance").update(status="confirming")
    # 更新流转事件中的验收中状态
    FlowEvent.objects.filter(from_status="acceptance").update(from_status="confirming")
    FlowEvent.objects.filter(to_status="acceptance").update(to_status="confirming")


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_replace_archived_with_cancelled"),
    ]

    operations = [
        # 先迁移数据，再修改字段定义
        migrations.RunPython(migrate_acceptance_tasks, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="flowevent",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("todo", "待处理"),
                    ("in_progress", "处理中"),
                    ("confirming", "待确认"),
                    ("overdue", "已超时"),
                    ("done", "已完成"),
                    ("cancel_pending", "待取消确认"),
                    ("cancelled", "已取消"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="flowevent",
            name="to_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("todo", "待处理"),
                    ("in_progress", "处理中"),
                    ("confirming", "待确认"),
                    ("overdue", "已超时"),
                    ("done", "已完成"),
                    ("cancel_pending", "待取消确认"),
                    ("cancelled", "已取消"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "待处理"),
                    ("in_progress", "处理中"),
                    ("confirming", "待确认"),
                    ("overdue", "已超时"),
                    ("done", "已完成"),
                    ("cancel_pending", "待取消确认"),
                    ("cancelled", "已取消"),
                ],
                default="todo",
                max_length=24,
            ),
        ),
    ]
