# Generated by Codex on 2026-04-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_user_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("tasks", "UserProfile")
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def copy_existing_owners_to_candidates(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    for task in Task.objects.exclude(owner_id__isnull=True):
        task.candidate_owners.add(task.owner_id)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0003_remove_acceptance_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "default_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_users",
                        to="tasks.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.department",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="candidate_owners",
            field=models.ManyToManyField(blank=True, related_name="candidate_tasks", to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_user_profiles, migrations.RunPython.noop),
        migrations.RunPython(copy_existing_owners_to_candidates, migrations.RunPython.noop),
    ]
