# Generated by Codex on 2026-04-25

from django.db import migrations


def backfill_default_departments(apps, schema_editor):
    Department = apps.get_model("tasks", "Department")
    Task = apps.get_model("tasks", "Task")
    UserProfile = apps.get_model("tasks", "UserProfile")

    fallback_department = Department.objects.order_by("id").first()
    for profile in UserProfile.objects.select_related("user").filter(default_department__isnull=True):
        recent_task = (
            Task.objects.filter(owner_id=profile.user_id, department_id__isnull=False)
            .order_by("-updated_at", "-id")
            .first()
        )
        profile.default_department = recent_task.department if recent_task else fallback_department
        if profile.default_department_id:
            profile.save(update_fields=["default_department"])


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_candidate_owners_user_profile"),
    ]

    operations = [
        migrations.RunPython(backfill_default_departments, migrations.RunPython.noop),
    ]
