# Generated by Django 4.2.20 on 2026-04-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_backfill_default_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_note",
            field=models.TextField(blank=True),
        ),
    ]
