# Generated by Django 4.2.20 on 2026-04-26 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0006_task_completion_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "创建"),
                    ("status", "状态变更"),
                    ("owner", "负责人变更"),
                    ("department", "部门变更"),
                    ("action", "操作"),
                    ("remind", "催办"),
                ],
                default="action",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="TaskReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("remind_type", models.CharField(choices=[("process_remind", "催处理"), ("confirm_remind", "催确认"), ("cancel_confirm_remind", "催取消确认")], max_length=32)),
                ("remark", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("from_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sent_task_reminders", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reminders", to="tasks.task")),
                ("to_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="received_task_reminders", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["task", "to_user", "-created_at"], name="tasks_taskr_task_id_04330d_idx"),
                    models.Index(fields=["remind_type", "-created_at"], name="tasks_taskr_remind__914cf8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=80)),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sent_task_notifications", to=settings.AUTH_USER_MODEL)),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_notifications", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="tasks.task")),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["recipient", "is_read", "-created_at"], name="tasks_taskn_recipie_872915_idx"),
                    models.Index(fields=["task", "-created_at"], name="tasks_taskn_task_id_ac7e7d_idx"),
                ],
            },
        ),
    ]
