# Generated by Django 4.2.20 on 2026-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_flowevent_event_type_taskreminder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasknotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_remind", "任务催办"),
                    ("task_completed", "任务已完成"),
                    ("task_cancel_requested", "任务取消申请"),
                    ("task_transferred", "任务流转"),
                    ("complete_confirm", "待完成确认"),
                    ("cancel_confirm", "待取消确认"),
                    ("task_timeout", "任务超时"),
                ],
                default="task_remind",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="tasknotification",
            index=models.Index(
                fields=["notification_type", "-created_at"],
                name="tasks_taskn_notific_cd372e_idx",
            ),
        ),
    ]
