# Generated by Django 4.2.20 on 2026-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_update_timestamp_fields_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="owner_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="责任人完成时间"
            ),
        ),
        migrations.AlterField(
            model_name="tasknotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_created", "新任务"),
                    ("task_remind", "任务催办"),
                    ("task_completed", "任务已完成"),
                    ("task_cancel_requested", "任务取消申请"),
                    ("task_transferred", "任务流转"),
                    ("complete_confirm", "待完成确认"),
                    ("cancel_confirm", "待取消确认"),
                    ("task_timeout", "任务超时"),
                ],
                default="task_remind",
                max_length=32,
            ),
        ),
    ]
