# Generated by Django 4.2.20 on 2026-04-27 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0011_add_owner_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="rework_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="重办时间"),
        ),
        migrations.AddField(
            model_name="task",
            name="rework_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reworked_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="重办发起人",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="rework_count",
            field=models.IntegerField(default=0, verbose_name="重办次数"),
        ),
        migrations.AddField(
            model_name="task",
            name="rework_reason",
            field=models.TextField(blank=True, verbose_name="重办原因"),
        ),
        migrations.AlterField(
            model_name="flowevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "创建"),
                    ("status", "状态变更"),
                    ("owner", "负责人变更"),
                    ("department", "部门变更"),
                    ("action", "操作"),
                    ("remind", "催办"),
                    ("rework", "重办"),
                ],
                default="action",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="tasknotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_created", "新任务"),
                    ("task_remind", "任务催办"),
                    ("task_completed", "任务已完成"),
                    ("task_cancel_requested", "任务取消申请"),
                    ("task_transferred", "任务流转"),
                    ("complete_confirm", "待完成确认"),
                    ("cancel_confirm", "待取消确认"),
                    ("task_timeout", "任务超时"),
                    ("task_reworked", "任务重办"),
                ],
                default="task_remind",
                max_length=32,
            ),
        ),
    ]
